name = "PrivateFields"
uuid = "f4800d5f-c5aa-4b4c-a966-fa01325904ff"
authors = ["Sam Buercklin <sam.buercklin@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.6"
MacroTools = "0.5.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
